Ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('', include('products.urls')),
    path('order', include('order.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
]

urlpatterns_api = [
    path('api/v0/account/', include('account.api.v0.urls')),
    path('api/v0/products/', include('products.api.v0.urls')),
    path('api/v0/orders/', include('order.api.v0.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

]
urlpatterns += urlpatterns_api



urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path

from . import views

app_name = 'order'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add/<int:pk>', views.add_order, name='add_order'),
    path('put/<int:pk>', views.put_order, name='put_order'),
    path('remove/<int:pk>', views.remove_order_item, name='remove_order_item')
]

products/api/v0/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('categories/', views.CategoryListAPIView.as_view(), name='category-list'),
    path('product/<int:pk>', views.ProductDetailAPIView.as_view(), name='product-detail'),
    path('products/', views.ProductListAPIView.as_view(), name='product-list'),
    path('products/<int:pk>/', views.ProductByCategoryListAPIView.as_view(), name='product_by_category'),
    path('comment-create/', views.CommentCreateAPIView.as_view(), name='comment-create'),

]

products/urls.py
from django.urls import path
from .views import *



urlpatterns = [
    path('', home, name='home'),
    path('products/<int:pk>', product_detail, name='product_detail'),
    path('store/', store, name='store'),
    path('category/<int:pk>/', get_category, name='category'),

]

products/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.contrib.auth import get_user_model
from django.core.validators import MinValueValidator, MaxValueValidator
from parler.models import TranslatedFields, TranslatableModel

from base.models import TimeStampModel
from products.choices import CategoryType

User = get_user_model()

class Category(TranslatableModel, TimeStampModel):
    translation = TranslatedFields(
        name=models.CharField(max_length=100, unique=True)
    )
    order = models.IntegerField(default=0)
    type = models.IntegerField(choices=CategoryType, default=CategoryType.NON_TYPE)

    def __str__(self):
        return self.name


class Product(TranslatableModel, TimeStampModel):
    translation = TranslatedFields(
        title=models.CharField(max_length=100),
        description = models.TextField(),
        detail=models.JSONField(default=dict)
    )
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, related_name='product')
    price = models.DecimalField(max_digits=20, decimal_places=2)
    quantity = models.IntegerField()

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.validate_detail()
        super().save(*args, **kwargs)


    def validate_detail(self):
        category_type = self.category.type
        if category_type == 1:
            required_keys = {'size', 'color'}
        else:
            required_keys = set()

        missing_keys = required_keys - self.detail.keys()
        if missing_keys:
            raise ValidationError(
                "Missing required keys for category type '%(category_type)s': %(missing_keys)s",
                params={'category_type': category_type, 'missing_keys': ', '.join(missing_keys)},
            )



class Images(TimeStampModel):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product/')
    is_main = models.BooleanField(default=False)


    def __str__(self):
        return f"{self.product.title}"


class Comment(TimeStampModel):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="comments")
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    text = models.CharField(max_length=300)
    star = models.IntegerField(default=0,
                               validators=[MaxValueValidator(5), MinValueValidator(0)])


    def __str__(self):
        return self.product.title

products/api/v0/views.py
from django.db.models import Prefetch, OuterRef, Subquery
from rest_framework import generics, status
from rest_framework.permissions import IsAuthenticated, IsAuthenticatedOrReadOnly
from rest_framework.response import Response
from rest_framework.views import APIView
from django.core.cache import cache
from .serializers import CategorySerializer, ProductSerializer, ProductDetailSerializer, CommentCreateSerializer
from ...models import Category, Product, Comment, Images


class CategoryListAPIView(generics.ListAPIView):
    serializer_class = CategorySerializer
    permission_classes = (IsAuthenticatedOrReadOnly,)

    def get_queryset(self):
        category_list = cache.get('category_list')
        if category_list is None:
            category_list = Category.objects.all()
            cache.set('category_list', category_list)
        return category_list
    # def get_queryset(self):
    #     qs = super().get_queryset()
    #     ids = [1, 3]
    #     qs = qs.filter(id__in=ids)
    #     return qs

class ProductListAPIView(generics.ListAPIView):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    permission_classes = (IsAuthenticatedOrReadOnly,)


    def get_queryset(self):
        products = cache.get('product_list')
        if products is None:
            # products = Product.objects.prefetch_related(
            #     Prefetch('images_set', queryset=Images.objects.order_by('id'))
            #
            # )
            main_image_subquery = Images.objects.filter(
                product=OuterRef('pk'),
                # is_main=True
            ).values('image')[:1]
            products = Product.objects.annotate(
                main_image=Subquery(main_image_subquery)
            )
            cache.set('product_list', products)
        # cache.delete('product_list')
        return products


class ProductByCategoryListAPIView(generics.ListAPIView):
    serializer_class = ProductSerializer
    permission_classes = (IsAuthenticatedOrReadOnly, )

    def get_queryset(self):
        category_id = self.kwargs.get('pk')
        cache_key = f'products_by_category_{category_id}'
        products_by_category = cache.get(cache_key)

        if products_by_category is None:
            main_image_subquery = Images.objects.filter(
                product=OuterRef('pk'),
                is_main=True
            ).values('image')[:1]

            products = Product.objects.filter(category_id=category_id).annotate(
                main_image=Subquery(main_image_subquery)
            )
            cache.set(cache_key, products)
            products_by_category = products

        return products_by_category

    # def get_queryset(self):
    #     qs = super().get_queryset()
    #     pk = self.kwargs.get('pk')
    #     qs = qs.filter(category=pk)
    #     return qs

class ProductDetailAPIView(generics.RetrieveAPIView):
    serializer_class = ProductDetailSerializer
    permission_classes = (IsAuthenticatedOrReadOnly, )

    def get_queryset(self):
        pk = self.kwargs.get('pk')
        product_detail = cache.get(f'product_detail_{pk}')
        if product_detail is None:
            queryset = Product.objects.select_related('category'
                                                      ).prefetch_related('images_set').all()
            cache.set(f'product_detail_{pk}', queryset)
        return product_detail





# class CommentCreateView(APIView):
#     permission_classes = ()
#     def post(self, request):
#         comment = CommentCreateSerializer(data=request.data)
#         if comment.is_valid():
#             comment.save()
#         return Response({"message":"Successfully created!"}, status=status.HTTP_201_CREATED)




class CommentCreateAPIView(generics.CreateAPIView):
    queryset = Comment.objects.all()
    serializer_class = CommentCreateSerializer
    permission_classes = (IsAuthenticated, )

    def perform_create(self, serializer):
        serializer.save(owner=self.request.user)

products/views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import OuterRef, Subquery, F, Avg, Prefetch
from django.shortcuts import render, get_object_or_404, redirect
from products.models import Product, Images, Comment, Category
from django.urls import reverse
from django.contrib.auth import get_user_model

User = get_user_model()


def home(request):
    categories = Category.objects.all()
    category_id = request.GET.get('category')

    if category_id:
        products = Product.objects.filter(category_id=category_id)
    else:
        products = Product.objects.all()

    main_image_subquery = Images.objects.filter(
        product=OuterRef('pk'),
        is_main=True
    ).values('image')[:1]

    products = products.annotate(
        main_image=Subquery(main_image_subquery)
    ).values('pk', 'price', 'main_image')[:8] # title

    context = {
        'products': products,
        'categories': categories,
    }

    return render(request, 'home.html', context)





def store(request):
    main_image_subquery = Images.objects.filter(
        product=OuterRef('pk'),
        # is_main=True
    ).values('image')[:1]

    price_gte = request.GET.get('price__gte')
    price_lte = request.GET.get('price__lte')
    if price_lte and price_gte:
        products = Product.objects.filter(price__gte=price_gte, price__lte=price_lte)
    elif price_gte and not price_lte:
        products = Product.objects.filter(price__gte=price_gte)
    else:
        products = Product.objects.all()

    products = products.annotate(
        main_image=Subquery(main_image_subquery)
    ).values('pk', 'title', 'price', 'main_image')

    products = Paginator(products, 3)
    page = request.GET.get('page')
    try:
        products = products.page(page)
    except (PageNotAnInteger, EmptyPage):
        products = products.page(1)

    # products = ProductFilter(request.GET, queryset=page_products.object_list)
    context = {'products': products}
    return render(request, 'product/store.html', context)

def get_category(request, pk):
    category = get_object_or_404(Category, pk=pk)
    main_image_subquery = Images.objects.filter(
        product=OuterRef('pk'),
        # is_main=True
    ).values('image')[:1]

    products = Product.objects.filter(category=category).annotate(
        main_image=Subquery(main_image_subquery)
    ).values('pk', 'title', 'price', 'main_image')

    products = Paginator(products, 3)
    page = request.GET.get('page')
    try:
        products = products.page(page)
    except (PageNotAnInteger, EmptyPage):
        products = products.page(1)

    context = {'products': products, "category": category}
    return render(request, 'product/store.html', context)


def product_detail(request, pk):
    product = get_object_or_404(Product, pk=pk)
    if request.method == "POST":
        text = request.POST.get('text')
        star = request.POST.get('star')
        if request.user.is_authenticated:
            comment = Comment.objects.create(
                product=product,
                owner=request.user,
                text=text,
                star=star if star else 0
            )
            return redirect(reverse('product_detail', kwargs={"pk": product.pk}))
    avg_rating = product.comments.filter(star__gt=0).aggregate(Avg('star'))['star__avg']
    context = {"product": product, "star_avg": avg_rating}
    return render(request, 'product/product_detail.html', context)

templates/product/product_detail.html
{% extends 'base.html' %}
{% load static %}
{% load star_range %}

{% block title %} {{ product.title }} {% endblock %}


{% block content %}


    <section class="section-content padding-y bg">
        <div class="container">

            <!-- ============================ COMPONENT 1 ================================= -->
            <div class="card">
                <div class="row no-gutters">
                    <aside class="col-md-6">
                        <article class="gallery-wrap">
                            <div class="img-big-wrap">
                                {% for img in product.images_set.all %}
                                    <a href="#"><img src="{{ img.image.url }}"></a>
                                {% endfor %}
                            </div> <!-- img-big-wrap.// -->

                        </article> <!-- gallery-wrap .end// -->
                    </aside>
                    <main class="col-md-6 border-left">
                        <article class="content-body">

                            <h2 class="title">{{ product.title }}</h2>

                            <div class="mb-3">
                                <var class="price h4">${{ product.price }}</var>
                            </div>

                            <p>{{ product.description }}</p>


                            <hr>
                            <div class="row">
                                <div class="item-option-select">
                                    <h6>Detail Color</h6>
                                    <div class="btn-group btn-group-sm btn-group-toggle" data-toggle="buttons">
                                        <label class="btn btn-light">
                                            {% if product.category.type == 1 %}
                                                <input type="radio" name="radio_color"> {{ product.detail.color }}
                                            {% else %}
                                                <input type="radio" name="radio_color"> {{ product.detail }}
                                            {% endif %}
                                        </label>
                                    </div>
                                </div>
                            </div> <!-- row.// -->
                            <hr>
                            <div class="row">
                                <div class="item-option-select">
                                    <h6>Detail Size</h6>
                                    <div class="btn-group btn-group-sm btn-group-toggle" data-toggle="buttons">
                                        <label class="btn btn-light">
                                            {% if product.category.type == 1 %}
                                                <input type="radio" name="radio_color"> {{ product.detail.size }}
                                            {% else %}
                                                <input type="radio" name="radio_color"> {{ product.detail }}
                                            {% endif %}
                                        </label>
                                    </div>
                                </div>
                            </div> <!-- row.// -->
                            <hr>
                            <a href="{% url 'order:add_order' product.pk %}" class="btn  btn-primary"> <span
                                    class="text">Add to cart</span> <i class="fas fa-shopping-cart"></i> </a>
                        </article> <!-- product-info-aside .// -->
                    </main> <!-- col.// -->
                </div> <!-- row.// -->
            </div> <!-- card.// -->
            <!-- ============================ COMPONENT 1 END .// ================================= -->

            <br>
            <div class="row">
                <div class="col-md-9">
                    <form method="post">
                        {% csrf_token %}
                        <label>Text</label>
                        <input type="text" name="text" placeholder="Text">
                        <label>Star</label>
                        <input name="star" type="number" placeholder="0", value="0">

                        <button type="submit"> Send</button>
                    </form>
                </div>
            </div>

            <div class="row">
                <div class="col-md-9">

                    <header class="section-heading">
                        <h3>Customer Reviews </h3>

                    </header>
                    {% for comment in product.comment_set.all %}
                        <article class="box mb-3">
                            <div class="icontext w-100">
                                <img src="{{  profile.avatar  }}" class="img-xs icon rounded-circle">
                                <div class="text">
                                    <span class="date text-muted float-md-right">{{ comment.created_at }} </span>
                                    <h6 class="mb-1">{{ comment.owner.username }}</h6>

                                </div>
                            </div> <!-- icontext.// -->
                            <div class="mt-3">
                                <p>
                                    {% for _ in comment.star|custom_range %}
                                        <span class="fa fa-star"></span>
                                    {% endfor %}
                                </p>
                                <p>
                                    {{ comment.text }}
                                </p>
                            </div>
                        </article>
                    {% endfor %}


                </div> <!-- col.// -->
            </div> <!-- row.// -->


        </div> <!-- container .//  -->
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->


{% endblock %}

templates/product/store.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
     {% if category %}
        {{ category.name }}
    {% else %}
        Store
    {% endif %}
{% endblock %}


{% block content %}


    <!-- ========================= SECTION PAGETOP ========================= -->
    <section class="section-pagetop bg">
        <div class="container">
            <h2 class="title-page">Our Store</h2>

        </div> <!-- container //  -->
    </section>
    <!-- ========================= SECTION INTRO END// ========================= -->

    <!-- ========================= SECTION CONTENT ========================= -->
    <section class="section-content padding-y">
        <div class="container">

            <div class="row">
                <aside class="col-md-3">
                    <form method="get">
                        {#                    {{ products.form.as_p }}#}
                        <div class="card">
                            <article class="filter-group">
                                <header class="card-header">
                                    <a href="#" data-toggle="collapse" data-target="#collapse_1" aria-expanded="true"
                                       class="">
                                        <i class="icon-control fa fa-chevron-down"></i>
                                        <h6 class="title">Categories</h6>
                                    </a>
                                </header>
                                <div class="filter-content collapse show" id="collapse_1" style="">
                                    <div class="card-body">

                                        <ul class="list-menu">
                                            {% for category in categories %}
                                                <li><a href="{% url 'category' category.pk %}">{{ category.name }} </a></li>
                                            {% endfor %}
                                        </ul>

                                    </div> <!-- card-body.// -->
                                </div>
                            </article> <!-- filter-group  .// -->

                            <article class="filter-group">
                                <header class="card-header">
                                    <a href="#" data-toggle="collapse" data-target="#collapse_3" aria-expanded="true"
                                       class="">
                                        <i class="icon-control fa fa-chevron-down"></i>
                                        <h6 class="title">Price range </h6>
                                    </a>
                                </header>
                                <div class="filter-content collapse show" id="collapse_3" style="">
                                    <div class="card-body">

                                        <div class="form-row">
                                            <div class="form-group col-md-6">
                                                <label>Min</label>
                                                <!-- <input class="form-control" placeholder="$0" type="number"> -->
                                                <select name="price__gte" class="mr-2 form-control">
                                                    <option value="0">$0</option>
                                                    <option value="50">$50</option>
                                                    <option value="100">$100</option>
                                                    <option value="150">$150</option>
                                                    <option value="200">$200</option>
                                                    <option value="500">$500</option>
                                                    <option value="1000">$1000</option>
                                                </select>
                                            </div>
                                            <div class="form-group text-right col-md-6">
                                                <label>Max</label>
                                                <select name="price__lte" class="mr-2 form-control">
                                                    <option></option>
                                                    <option value="50">$50</option>
                                                    <option value="100">$100</option>
                                                    <option value="150">$150</option>
                                                    <option value="200">$200</option>
                                                    <option value="500">$500</option>
                                                    <option value="1000">$1000</option>
                                                    <option value="2000">$2000+</option>
                                                </select>
                                            </div>
                                        </div> <!-- form-row.// -->
                                        <button class="btn btn-block btn-primary">Apply</button>
                                    </div><!-- card-body.// -->
                                </div>
                            </article> <!-- filter-group .// -->

                        </div> <!-- card.// -->
                    </form>

                </aside> <!-- col.// -->
                <main class="col-md-9">

                    <header class="border-bottom mb-4 pb-3">
                        <div class="form-inline">
                            <span class="mr-md-auto">{{ products.object_list.count }} Items found </span>

                        </div>
                    </header><!-- sect-heading -->

                    <div class="row">
                        {% for product in products.object_list %}
                            <div class="col-md-4">
                                <figure class="card card-product-grid">
                                    <div class="img-wrap">

                                        <img src="/media/{{ product.main_image }}">

                                    </div> <!-- img-wrap.// -->
                                    <figcaption class="info-wrap">
                                        <div class="fix-height">
                                            <a href="{% url 'product_detail' product.pk %}"
                                               class="title">{{ product.title }}</a>
                                            <div class="price-wrap mt-2">
                                                <span class="price">${{ product.price }}</span>
                                                {#                                            <del class="price-old">$1980</del>#}
                                            </div> <!-- price-wrap.// -->
                                        </div>
                                        <a href="{% url 'order:add_order' product.pk %}" class="btn btn-block btn-success">Add to cart </a>
                                    </figcaption>
                                </figure>
                            </div> <!-- col.// -->
                        {% endfor %}
                    </div> <!-- row end.// -->


                    <nav class="mt-4" aria-label="Page navigation sample">
                        <ul class="pagination">
                            <li class="page-item">
                                {% if products.has_previous %}
                                    <a href="?page=1">&laquo; first</a>
                                    <a href="?page={{ products.previous_page_number }}">previous</a>
                                {% endif %}
                            </li>
                            <li class="page-item">
                                <span class="current">
                            Page {{ products.number }} of {{ products.paginator.num_pages }}.
                                </span>
                            </li>
                            <li class="page-item">
                                {% if products.has_next %}
                                    <a href="?page={{ products.next_page_number }}">next</a>
                                    <a href="?page={{ products.paginator.num_pages }}">last &raquo;</a>
                                {% endif %}
                            </li>
                        </ul>
                    </nav>

                </main> <!-- col.// -->

            </div>

        </div> <!-- container .//  -->
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->




{% endblock %}