Ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('', include('products.urls')),
    path('order', include('order.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
]

urlpatterns_api = [
    path('api/v0/account/', include('account.api.v0.urls')),
    path('api/v0/products/', include('products.api.v0.urls')),
    path('api/v0/orders/', include('order.api.v0.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

]
urlpatterns += urlpatterns_api



urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.urls import path

from .views import *

app_name = 'account'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', sign_up, name='register'),
    path('profile/', profile_view, name='profile'),
    path('profile/', profile_view, name='profile'),
    path('profile-edit/', profile_edit_view, name='profile_edit'),
    path('profile-delete/', profile_delete_view, name='profile_delete'),
]

order/urls.py
from django.urls import path

from . import views

app_name = 'order'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add/<int:pk>', views.add_order, name='add_order'),
    path('put/<int:pk>', views.put_order, name='put_order'),
    path('remove/<int:pk>', views.remove_order_item, name='remove_order_item')
]

base/models.py
from django.db import models

class TimeStampModel(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

base/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
{% load static %}
<!DOCTYPE HTML>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="pragma" content="no-cache"/>
    <meta http-equiv="cache-control" content="max-age=604800"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>{% block title %} {% endblock %}</title>

    <link href="{% static 'images/logo.png' %}" rel="shortcut icon" type="image/x-icon">

    <!-- jQuery -->
    <script src="{% static 'js/jquery-2.0.0.min.js' %}" type="text/javascript"></script>

    <!-- Bootstrap4 files-->
    <script src="{% static 'js/bootstrap.bundle.min.js' %}" type="text/javascript"></script>
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css"/>

    <!-- Font awesome 5 -->
    <link href="{% static 'fonts/fontawesome/css/all.min.css' %}" type="text/css" rel="stylesheet">

    <!-- custom style -->
    <link href="{% static 'css/ui.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'css/responsive.css' %}" rel="stylesheet" media="only screen and (max-width: 1200px)"/>

    <!-- custom javascript -->
    <script src="{% static 'js/script.js' %}" type="text/javascript"></script>

    <script type="text/javascript">
        /// some script

        // jquery ready start
        $(document).ready(function () {
            // jQuery code

        });
        // jquery end
    </script>

    
    
</head>
<body>
<div class="success-message">
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li class="{{ message.tags }}">
                    <h4 class="alert-{{ message.tag }} text-center" style="padding-top: 5px; padding-bottom: 5px;">
                        {{ message }}
                    </h4>
                </li>
            {% endfor %}
         </ul>
     {% endif %}

</div>
<!-- ========================= HEADER ========================= -->
{% include 'header.html' %}
<!-- ========================= HEADER END // ========================= -->


<!-- ========================= SECTION MAIN ========================= -->
{% block content %}

{% endblock %}

<!-- ========================= SECTION  END// ========================= -->


<!-- ========================= FOOTER ========================= -->
{% include 'footer.html' %}
<!-- ========================= FOOTER END // ========================= -->

</body>
</html>

templates/footer.html
<footer class="section-footer border-top">
	<div class="container">
		<section class="footer-bottom border-top row">
			<div class="col-md-2">
				<p class="text-muted"> &copy 2024 Usmonov Salokhiddin </p>
			</div>
			<div class="col-md-8 text-md-center">
				<span  class="px-2">usmonovsalokhiddin@gmail.com</span>
				<span  class="px-2">+998 97 198 24 29</span>
				<span  class="px-2">Street Zarkaynar 1</span>
			</div>
			<div class="col-md-2 text-md-right text-muted">
				<i class="fab fa-lg fa-cc-visa"></i>
				<i class="fab fa-lg fa-cc-paypal"></i>
				<i class="fab fa-lg fa-cc-mastercard"></i>
			</div>
		</section>
	</div><!-- //container -->
</footer>

templates/header.html
{% load static %}
<header class="section-header">
<nav class="navbar p-md-0 navbar-expand-sm navbar-light border-bottom">
<div class="container">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTop4" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTop4">
    <ul class="navbar-nav mr-auto">
    	<li class="nav-item dropdown">
		 	<a href="#" class="nav-link">   English </a>

		</li>
		<li class="nav-item dropdown">
			<a href="#" class="nav-link"> USD </a>
		</li>
    </ul>
    <ul class="navbar-nav">
		<li><a href="#" class="nav-link"> <i class="fa fa-envelope"></i> Email </a></li>
		<li><a href="#" class="nav-link"> <i class="fa fa-phone"></i> Call us </a></li>
	</ul> <!-- list-inline //  -->
  </div> <!-- navbar-collapse .// -->
</div> <!-- container //  -->
</nav>

<section class="header-main border-bottom">
	<div class="container">
<div class="row align-items-center">
	<div class="col-lg-2 col-md-3 col-6">
		<a href="{% url 'home' %}" class="brand-wrap">
			<img class="logo" src="{% static 'images/logo.png' %}">
		</a> <!-- brand-wrap.// -->
	</div>
	<div class="col-lg col-sm col-md col-6 flex-grow-0">
		<div class="category-wrap dropdown d-inline-block float-right">
			<button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
				<i class="fa fa-bars"></i> All category
			</button>
			<div class="dropdown-menu">
                {% for category in categories %}
				<a class="dropdown-item" href="{% url 'category' category.pk %}">{{ category.name }} </a>
                {% endfor %}
			</div>
		</div>  <!-- category-wrap.// -->
	</div> <!-- col.// -->
	<a href="{% url 'store' %}" class="btn btn-outline-primary">Store</a>
	<div class="col-lg  col-md-6 col-sm-12 col">
		<form action="#" class="search">
			<div class="input-group w-100">
			    <input type="text" class="form-control" style="width:60%;" placeholder="Search">

			    <div class="input-group-append">
			      <button class="btn btn-primary" type="submit">
			        <i class="fa fa-search"></i>
			      </button>
			    </div>
		    </div>
		</form> <!-- search-wrap .end// -->
	</div> <!-- col.// -->
	<div class="col-lg-3 col-sm-6 col-8 order-2 order-lg-3">
				<div class="d-flex justify-content-end mb-3 mb-lg-0">
					<div class="widget-header">
						<small class="title text-muted">Welcome guest!</small>
						<div>
                            {% if user.is_authenticated %}
							<a href="{% url 'account:profile' %}">{{ user.username }}</a> <span class="dark-transp"> | </span>
							<a href="{% url 'account:logout' %}"> Logout</a>
                            {% else %}
                            <a href="{% url 'account:login' %}">Sign in</a> <span class="dark-transp"> | </span>
							<a href="{% url 'account:register' %}"> Register</a>
                            {% endif %}
						</div>
					</div>
					<a href="{% url 'order:cart' %}" class="widget-header pl-3 ml-3">
						<div class="icon icon-sm rounded-circle border"><i class="fa fa-shopping-cart"></i></div>
						<span class="badge badge-pill badge-danger notify">{{ count }}</span>
					</a>
				</div> <!-- widgets-wrap.// -->
			</div> <!-- col.// -->
</div> <!-- row.// -->
	</div> <!-- container.// -->
</section> <!-- header-main .// -->




</header> <!-- section-header.// -->

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %} E-commerce {% endblock %}


{% block content %}

    <section class="section-intro padding-y-sm">
        <div class="container">

            <div class="intro-banner-wrap">
                <img src="{% static 'images/banners/1.jpg' %}" class="img-fluid rounded">
            </div>

        </div> <!-- container //  -->
    </section>
    <!-- ========================= SECTION MAIN END// ========================= -->

    <!-- ========================= SECTION  ========================= -->
    <section class="section-name padding-y-sm">
        <div class="container">

            <header class="section-heading">
                <a href="{% url 'store' %}" class="btn btn-outline-primary float-right">See all</a>
                <h3 class="section-title">Popular products</h3>
            </header><!-- sect-heading -->


            <div class="row">
                {% for product in products %}
                <div class="col-md-3">
                    <div class="card card-product-grid">
                        <a href="#" class="img-wrap">
                            {% if product.main_image %}
                            <img src="media/{{ product.main_image }}">
                            {% else %}11
                            <img src="{% static 'images/items/1.jpg' %}">
                            {% endif %}
                        </a>
                        <figcaption class="info-wrap">
                            <a href="{% url 'product_detail' product.pk %}" class="title">{{ product.title }}</a>
                            <div class="price mt-1">${{ product.price }}</div> <!-- price-wrap.// -->
                        </figcaption>
                    </div>
                </div> <!-- col.// -->
                {% endfor %}
            </div> <!-- row.// -->

        </div><!-- container // -->
    </section>


{% endblock %}

templates/messages.html
{% for message in messages %}
    <div class="alert {{ message.tags }} alert-dismissible shadow fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        {{ message | safe }}
    </div>
{% endfor %}