Ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('', include('products.urls')),
    path('order', include('order.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
]

urlpatterns_api = [
    path('api/v0/account/', include('account.api.v0.urls')),
    path('api/v0/products/', include('products.api.v0.urls')),
    path('api/v0/orders/', include('order.api.v0.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

]
urlpatterns += urlpatterns_api



urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/api/v0/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('cart/', views.CartByOwnerListAPIView.as_view(), name='cart'),
    path('add/<int:pk>/', views.add_order, name='add_order'),
    path('put/<int:pk>/', views.put_order, name='put_order'),
]

order/urls.py
from django.urls import path

from . import views

app_name = 'order'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add/<int:pk>', views.add_order, name='add_order'),
    path('put/<int:pk>', views.put_order, name='put_order'),
    path('remove/<int:pk>', views.remove_order_item, name='remove_order_item')
]

order/models.py
from django.db import models
from django.contrib.auth import get_user_model

from base.models import TimeStampModel
from products.models import Product

User = get_user_model()


class OrderItem(TimeStampModel):
    customer = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='product')
    quantity = models.PositiveIntegerField()
    total_price = models.DecimalField(max_digits=20, decimal_places=2, null=True, blank=True)
    ordered = models.BooleanField(default=False)
    order = models.ForeignKey("Order", on_delete=models.CASCADE, related_name='orderitem')

    def __str__(self):
        return self.product.title

    def set_total_price(self):
        self.total_price = self.product.price * self.quantity
        self.save()
        return


class Order(TimeStampModel):
    customer = models.ForeignKey(User, on_delete=models.CASCADE)
    total_price = models.DecimalField(max_digits=20, decimal_places=2, null=True, blank=True)
    ordered = models.BooleanField(default=False)

    def __str__(self):
        return self.customer.username

    # def set_total_price(self):
    #     total = 0
    #     for price in self.orderitem.objects.all():
    #         total += price.total_price
    #     self.total_price = total
    #     self.save()
    #     return

products/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.contrib.auth import get_user_model
from django.core.validators import MinValueValidator, MaxValueValidator
from parler.models import TranslatedFields, TranslatableModel

from base.models import TimeStampModel
from products.choices import CategoryType

User = get_user_model()

class Category(TranslatableModel, TimeStampModel):
    translation = TranslatedFields(
        name=models.CharField(max_length=100, unique=True)
    )
    order = models.IntegerField(default=0)
    type = models.IntegerField(choices=CategoryType, default=CategoryType.NON_TYPE)

    def __str__(self):
        return self.name


class Product(TranslatableModel, TimeStampModel):
    translation = TranslatedFields(
        title=models.CharField(max_length=100),
        description = models.TextField(),
        detail=models.JSONField(default=dict)
    )
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, related_name='product')
    price = models.DecimalField(max_digits=20, decimal_places=2)
    quantity = models.IntegerField()

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.validate_detail()
        super().save(*args, **kwargs)


    def validate_detail(self):
        category_type = self.category.type
        if category_type == 1:
            required_keys = {'size', 'color'}
        else:
            required_keys = set()

        missing_keys = required_keys - self.detail.keys()
        if missing_keys:
            raise ValidationError(
                "Missing required keys for category type '%(category_type)s': %(missing_keys)s",
                params={'category_type': category_type, 'missing_keys': ', '.join(missing_keys)},
            )



class Images(TimeStampModel):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product/')
    is_main = models.BooleanField(default=False)


    def __str__(self):
        return f"{self.product.title}"


class Comment(TimeStampModel):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="comments")
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    text = models.CharField(max_length=300)
    star = models.IntegerField(default=0,
                               validators=[MaxValueValidator(5), MinValueValidator(0)])


    def __str__(self):
        return self.product.title

order/api/v0/views.py
from django.db import IntegrityError
from django.shortcuts import get_object_or_404
from rest_framework import generics
from rest_framework.decorators import api_view, permission_classes
from rest_framework.response import Response
from rest_framework import status
from rest_framework.permissions import IsAuthenticated
from django.core.cache import cache



from products.models import Product
from .permissions import IsOrderOwner
from .serializers import OrderSerializer
from order.models import Order, OrderItem


class CartByOwnerListAPIView(generics.ListAPIView):
    queryset = Order.objects.all()
    serializer_class = OrderSerializer
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        pk = self.request.user.pk
        cardorederby = cache.get(f'cardorederby_{pk}')
        if cardorederby is None:
            cardorederby =  Order.objects.all()
            cache.set('cardorederby_{pk}', cardorederby)
        return cardorederby

    # def get_queryset(self):
    #     qs = super().get_queryset()
    #     qs = qs.filter(customer=self.request.user, ordered=False)
    #     return qs



@api_view(['POST'])
@permission_classes([IsOrderOwner])
def add_order(request, pk):
    product = get_object_or_404(Product, pk=pk)
    order, order_created = Order.objects.get_or_create(
        customer=request.user,
        ordered=False
    )


    try:
        order_item, order_item_created = OrderItem.objects.get_or_create(
            product=product,
            customer=request.user,
            ordered=False,
            order=order

        )
    except IntegrityError:
        order_item, order_item_created = OrderItem.objects.get_or_create(
            product=product,
            customer=request.user,
            quantity=1,
            ordered=False,
            order=order

        )
    order_item.set_total_price()
    if not order_item_created:
        order_item.quantity += 1
        order_item.save()
        order_item.set_total_price()
        return Response({'message': "1 ga oshirildi"}, status=status.HTTP_201_CREATED)
    return Response({'message': "order yaratildi"}, status=status.HTTP_201_CREATED)


@api_view(['POST'])
@permission_classes([IsAuthenticated, IsOrderOwner])
def put_order(request, pk):
    product = get_object_or_404(Product, pk=pk)
    order, order_created = Order.objects.get_or_create(
        customer=request.user,
        ordered=False
    )

    try:
        order_item, order_item_created = OrderItem.objects.get_or_create(
            product=product,
            customer=request.user,
            ordered=False,
            order=order

        )
    except IntegrityError:
        order_item, order_item_created = OrderItem.objects.get_or_create(
            product=product,
            customer=request.user,
            quantity=1,
            ordered=False,
            order=order

        )
    order_item.set_total_price()
    if order_item.quantity > 1:
        order_item.quantity -= 1
        order_item.save()
        order_item.set_total_price()
        return Response({'message': "1 ga kamaydi"}, status=status.HTTP_201_CREATED)
    else:
        order_item.delete()
        return Response({'message': "order uchirildi"}, status=status.HTTP_201_CREATED)

order/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import F, Sum
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.db import IntegrityError

from order.models import Order, OrderItem
from products.models import Product


@login_required(login_url='/account/login/')
def cart(request):
    order = Order.objects.filter(customer=request.user,
                                 ordered=False).annotate(
        order_total_price=Sum('orderitem__total_price')
    ).first()

    context = {
        'order': order
    }
    return render(request, 'order/cart.html', context=context)


@login_required(login_url='/account/login/')
def add_order(request, pk):
    product = get_object_or_404(Product, pk=pk)
    order, order_created = Order.objects.get_or_create(
        customer=request.user,
        ordered=False
    )

    try:
        order_item, order_item_created = OrderItem.objects.get_or_create(
            product=product,
            customer=request.user,
            ordered=False,
            order=order

        )
    except IntegrityError:
        order_item, order_item_created = OrderItem.objects.get_or_create(
            product=product,
            customer=request.user,
            quantity=1,
            ordered=False,
            order=order

        )
    order_item.set_total_price()
    if not order_item_created:
        order_item.quantity += 1
        order_item.save()
        order_item.set_total_price()
        messages.info(request, f'{product.title} 1 ga oshirildi!')
        return redirect('order:cart')


    messages.info(request, 'savatchaga qo`shildi!')
    return redirect('order:cart')


@login_required(login_url='/account/login/')
def put_order(request, pk):
    product = get_object_or_404(Product, pk=pk)
    order, order_created = Order.objects.get_or_create(
        customer=request.user,
        ordered=False
    )

    try:
        order_item, order_item_created = OrderItem.objects.get_or_create(
            product=product,
            customer=request.user,
            ordered=False,
            order=order

        )
    except IntegrityError:
        order_item, order_item_created = OrderItem.objects.get_or_create(
            product=product,
            customer=request.user,
            quantity=1,
            ordered=False,
            order=order

        )
    order_item.set_total_price()
    if order_item.quantity > 1:
        order_item.quantity -= 1
        order_item.save()
        order_item.set_total_price()
        messages.info(request, f'{product.title} 1 ga ayrildi!')
        return redirect('order:cart')
    else:
        order_item.delete()



    messages.info(request, 'savatchaga qo`shildi!')
    return redirect('order:cart')



@login_required(login_url='/account/login/')
def remove_order_item(request, pk):
    order_item = get_object_or_404(OrderItem, pk=pk)
    order_item.delete()
    return redirect('order:cart')

templates/order/cart.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block title %} Cart {% endblock %}

{% block content %}


    <section class="section-content padding-y bg">
        <div class="container">

            <!-- ============================ COMPONENT 1 ================================= -->

            <div class="row">
                <aside class="col-lg-9">
                    <div class="card">
                        <table class="table table-borderless table-shopping-cart">
                            <thead class="text-muted">
                            <tr class="small text-uppercase">
                                <th scope="col">Product</th>
                                <th scope="col" width="120">Quantity</th>
                                <th scope="col" width="120">Price</th>
                                <th scope="col" class="text-right" width="200"></th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for order_item in order.orderitem.all %}
                            <tr>
                                <td>
                                    <figure class="itemside align-items-center">
                                        {% for img in order_item.product.images_set.all %}
                                            {% if forloop.first %}
                                        <div class="aside"><img src="{{ img.image.url }}" class="img-sm"></div>
                                            {% endif %}
                                            {% endfor %}
                                        <figcaption class="info">
                                            <a href="#" class="title text-dark">{{ order_item.product.title }}</a>
                                            <p class="text-muted small">detail </p>
                                        </figcaption>
                                    </figure>
                                </td>
                                <td>
                                    <!-- col.// -->
                                    <div class="col">
                                        <div class="input-group input-spinner">
                                            <div class="input-group-prepend">
                                                 <a href="{% url 'order:put_order' order_item.product.pk %}" class="btn btn-light"  type="button" id="button-plus"><i
                                                        class="fa fa-minus"></i></a>
                                            </div>
                                            <input type="text" class="form-control" value="{{ order_item.quantity }}">
                                            <div class="input-group-append">
                                                <a href="{% url 'order:add_order' order_item.product.pk %}" class="btn btn-light"  type="button" id="button-plus"><i
                                                        class="fa fa-plus"></i></a>
                                            </div>
                                        </div> <!-- input-group.// -->
                                    </div> <!-- col.// -->
                                </td>
                                <td>
                                    <div class="price-wrap">
                                        <var class="price">${{ order_item.total_price }}</var>
                                        <small class="text-muted"> ${{ order_item.product.price }} each </small>
                                    </div> <!-- price-wrap .// -->
                                </td>
                                <td class="text-right">
                                    <a href="{% url 'order:remove_order_item' order_item.pk %}" class="btn btn-danger"> Remove</a>
                                </td>
                            </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div> <!-- card.// -->

                </aside> <!-- col.// -->
                <aside class="col-lg-3">

                    <div class="card">
                        <div class="card-body">
                            <dl class="dlist-align">
                                <dt>Total price:</dt>
                                <dd class="text-right">${{ order.order_total_price|floatformat:2|intcomma }}</dd>
                            </dl>
                            <dl class="dlist-align">
                                <dt>Tax:</dt>
                                <dd class="text-right"> $10.00</dd>
                            </dl>
                            <dl class="dlist-align">
                                <dt>Total:</dt>
                                <dd class="text-right text-dark b"><strong>${{ order.order_total_price|add:10|floatformat:2|intcomma }}</strong></dd>
                            </dl>
                            <hr>
                            <p class="text-center mb-3">
                                <img src="{% static 'images/misc/payments.png' %}" height="26">
                            </p>
                            <a href="./place-order.html" class="btn btn-primary btn-block"> Checkout </a>
                            <a href="./store.html" class="btn btn-light btn-block">Continue Shopping</a>
                        </div> <!-- card-body.// -->
                    </div> <!-- card.// -->

                </aside> <!-- col.// -->


            </div> <!-- row.// -->
            <!-- ============================ COMPONENT 1 END .// ================================= -->

        </div> <!-- container .//  -->
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock %}